### ISSUE TITLE
Impossible to uninstall package

### ISSUE THREAD

**Issue by slimndap** [slushman/atom-wp-dev#2]
If you try to uninstall the package you get an 'Uninstalling wp-dev failed' error.

![uninstall](https://cloud.githubusercontent.com/assets/2284714/16461219/c18c0f4c-3e2b-11e6-82b4-25beb6f9e159.gif)

**Comment by slushman** [comment]
Thanks for reporting that! I'll look into what's going on there, it definitely shouldn't do that.

**Comment by slushman** [comment]
Hey Jeroen,
Looks like this is an Atom issue. They say its fixed in the upcoming v1.9. I'll leave this issue open until that's proven.

https://github.com/atom/atom/issues/11464

**Comment by slimndap** [comment]
ok! thanks for the update.

**Comment by slushman** [comment]
Hey Jeroen,
This is now fixed in the 1.9 update to Atom. Thanks for reporting!
